[package]
name = "bitboard"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "bitboard"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
magpie = { version = "0.9.0", features = ["serde"] }
rustler = "0.22.0"
